# Generated by Django 5.0.14 on 2026-05-18 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('hostname', models.CharField(blank=True, max_length=150, null=True)),
                ('firefox_status', models.CharField(choices=[('running', 'Executando'), ('closed', 'Fechado'), ('unknown', 'Desconhecido')], default='unknown', max_length=20)),
                ('audio_status', models.CharField(choices=[('playing', 'Tocando'), ('silent', 'Sem Áudio'), ('unknown', 'Desconhecido')], default='unknown', max_length=20)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
