# Generated by Django 5.0.14 on 2026-05-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineheartbeat',
            name='silent_streak',
            field=models.IntegerField(default=0),
        ),
    ]
